### ISSUE TITLE
Implement Draining Kiss

### ISSUE THREAD

**Issue by Tapin42** [rushanshekar/gen6-damage-calc#29]
http://nuggetbridge.com/forums/topic/13620-introducing-the-nugget-bridge-pokémon-damage-calculator/?p=178429

Not sure if this was left unimplemented because it has a heal component, but Drain Punch should be quite similar if the calc deals with it at all.

**Comment by augmt** [comment]
Since there's no competitive Pokemon set that has Draining Kiss in its movelist, Draining Kiss and other uncommon moves (e.g., Luster Purge, Mud Bomb, Inferno, and Fell Stinger) aren't included in move_data.js. (Or at least that's why I haven't included them.)

Nucleose is right about the move not being hard to make though.

**Comment by Tapin42** [comment]
I'll stick those in since they're easy.  Thanks for the background!
